Route26Sign_Text::
    .string "ROUTE 26\n"
    .string "POKéMON LEAGUE RECEPTION GATE$"

Route26_Text_BethIntro::
	.string "I lost to a trainer named <RIVAL>.\n"
    .string "He was really strong, but…\p"
    .string "It was as if he absolutely had to\n"
	.string "win at any cost.\p"
    .string "I felt sorry for his POKéMON.$"

Route26_Text_BethRematchIntro::
	.string "Do you want to battle? I'm going\n"
	.string "to win this time!$"

Route26_Text_BethDefeat::
	.string "POKéMON aren't tools of war.$"

Route26_Text_BethPostBattle::
	.string "POKéMON are invaluable, lifelong\n"
	.string "partners.$"

Route26_Text_JakeIntro::
	.string "I'm making my final preparations\n"
	.string "for the POKéMON LEAGUE.$"

Route26_Text_JakeRematchIntro::
	.string "Do you want to help me train for the\n"
	.string "POKéMON LEAGUE?$"

Route26_Text_JakeDefeat::
	.string "I blew it!$"

Route26_Text_JakePostBattle::
	.string "It's going to be tough to win at\n"
	.string "the POKéMON LEAGUE.\p"
	.string "I need to do some more training.\n"
	.string "I hear that the LEAGUE's ELITE\p"
	.string "FOUR are tougher than GYM LEADERS.$"

Route26_Text_GavenIntro::
	.string "By experiencing tough battles, you\n"
	.string "gain power.$"

Route26_Text_GavenRematchIntro::
	.string "Want to experience another tough battle?$"

Route26_Text_GavenDefeat::
	.string "Gaah! Life is even tougher!$"

Route26_Text_GavenPostBattle::
	.string "To get to the POKéMON LEAGUE, you\n"
	.string "have to get through VICTORY ROAD.\p"
	.string "But VICTORY ROAD is tough. Practically\n"
	.string "nobody goes there!$"

Route26_Text_JoyceIntro::
	.string "Since you've come this far, you\n"
	.string "must be good.\p"
	.string "I'm going to give this battle\n"
	.string "everything I've got!$"

Route26_Text_JoyceRematchIntro::
	.string "I'm ready to give this rematch\n"
	.string "everything I've got!$"

Route26_Text_JoyceDefeat::
	.string "No! I don't believe this!$"

Route26_Text_JoycePostBattle::
	.string "I've defeated eight GYM LEADERS,\n"
	.string "so I was feeling confident. I'll\p"
	.string "have to try harder next time.$"

Route26_Text_JoeyIntro::
	.string "Ah! Perhaps battling you will\n"
	.string "offer a real challenge!\p"

Route26_Text_JoeyRematchIntro::
	.string "Are you sure you want to\n"
	.string "challenge me again?$"

Route26_Text_JoeyDefeat::
	.string "Rats, I lost!$"

Route26_Text_JoeyPostBattle::
	.string "Good luck in the POKéMON LEAGUE!$"
